version: "3.8"

services:
  web:
    build: .
    command: "gunicorn main.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/app
      - ./static:/home/app/web/static
    environment:
      - ALLOWED_HOSTS=127.0.0.1 localhost [::]
      - SECRET_KEY=django-insecure-^+d(k8pn^=g3e7@+@&6)qb$#oe24llxdg+7ajx+a)p=w$x@tl^
      - DEBUG=0

  nginx:
    image: nginx:1.25-alpine3.17-slim
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - ./static:/home/app/web/static
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always